<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>AWS-XERO</groupId>
  <artifactId>xd-hax-17</artifactId>
  <packaging>war</packaging>
  <version>0.0.1-SNAPSHOT</version>
  <name>xd-hax-17 Maven Webapp</name>
  <url>http://maven.apache.org</url>
   <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
		<groupId>javax.servlet</groupId>
		<artifactId>javax.servlet-api</artifactId>
		<version>3.1.0</version>
	</dependency>
	<dependency>
	  <groupId>com.xero</groupId>
	  <artifactId>xero-java-sdk</artifactId>
	  <version>0.4.4</version>
	</dependency>
	<dependency>
	  <groupId>com.amazonaws</groupId>
	  <artifactId>aws-java-sdk-s3</artifactId>
	</dependency>
	<dependency>
		<groupId>com.amazonaws</groupId>
		<artifactId>aws-java-sdk-cognitoidentity</artifactId>
	</dependency>
	<dependency>
    <groupId>com.amazonaws</groupId>
	    <artifactId>aws-java-sdk-cognitoidp</artifactId>
	</dependency>
	<dependency>
	    <groupId>com.amazonaws</groupId>
	    <artifactId>aws-java-sdk-dynamodb</artifactId>
	</dependency>
	<dependency>
	    <groupId>com.amazonaws</groupId>
	    <artifactId>aws-java-sdk-ses</artifactId>
	</dependency>
	<dependency>
       <groupId>com.amazonaws</groupId>
       <artifactId>DynamoDBLocal</artifactId>
       <version>2.1.0</version>
    </dependency>
  </dependencies>
  <dependencyManagement>
	<dependencies>
	    <dependency>
	      <groupId>com.amazonaws</groupId>
	      <artifactId>aws-java-sdk-bom</artifactId>
	      <version>1.11.106</version>
	      <type>pom</type>
	      <scope>import</scope>
	    </dependency>
	  </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
       <id>dynamodb-local-oregon</id>
       <name>DynamoDB Local Release Repository</name>
       <url>https://s3-us-west-2.amazonaws.com/dynamodb-local/release</url>
    </repository>

    <repository>
      <id>xero-java-mvn-repo</id>
	  <url>https://raw.github.com/SidneyAllen/Xero-Java/mvn-repo/</url>
	  <snapshots>
	    <enabled>true</enabled>
	    <updatePolicy>always</updatePolicy>
	  </snapshots>
    </repository>
  </repositories>
  <build>
    <finalName>xd-hax-17</finalName>
  </build>
</project>
